/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2024-01-06 06:51:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Footer</title>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/global.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footer.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footerbootStrap.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/footerModal.css\">\n");
      out.write("	<script src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/footerModal.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"custom-shape-divider-bottom-1685198268\">\n");
      out.write("            <!-- <svg data-name=\"Layer 1\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 120\" preserveAspectRatio=\"none\">\n");
      out.write("                <path d=\"M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z\" class=\"shape-fill\"></path>\n");
      out.write("            </svg> -->\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <section class=\"footerSection\">\n");
      out.write("          \n");
      out.write("            <section class=\"footerFirstSec\">\n");
      out.write("                <div>\n");
      out.write("                    <span>Company</span>\n");
      out.write("                    <span>Information</span>\n");
      out.write("                    <span>Contact</span>\n");
      out.write("                    <span class=\"displayNone\">(주) 기타치는 오리</span>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"footerSecSec\">\n");
      out.write("                <div class=\"firstDiv\">\n");
      out.write("                    <ul class=\"firstUl\">\n");
      out.write("                        <li id=\"asd\">대표 : 조미현</li>\n");
      out.write("                        <li>서비스명 : Band Archive</li>\n");
      out.write("                        <li>사업자 번호 : 120-87-1233043</li>\n");
      out.write("                        <li>통신 판매 : 제2023-서울강남-01234</li>\n");
      out.write("                        <li>작업정보제공 : J120000201900002</li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"secondDiv\">\n");
      out.write("                    <ul class=\"secondUl\">\n");
      out.write("                        <li><a href=\"#\" class=\"footer1-modal-toggle\">공지사항</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"footer2-modal-toggle\">이용약관</a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"footer3-modal-toggle\">개인정보처리방침</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"thirdDiv\">\n");
      out.write("                    <ul class=\"thirdUl\">\n");
      out.write("                        <li><i class=\"bi bi-envelope\"></i>&nbsp;&nbsp; gosrod05@gmail.com</li></li>\n");
      out.write("                        <li><i class=\"bi bi-geo-alt\"></i>&nbsp;&nbsp;서울시 강남구 테헤란로 12 3층</li></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("        \n");
      out.write("	        <section class=\"footerThirdSec\">\n");
      out.write("	            <div class=\"socialdiv\">\n");
      out.write("	                <ul class=\"forthUl\">\n");
      out.write("	                    <li><i class=\"bi bi-envelope\"></i></li>\n");
      out.write("	                    <li><i class=\"bi bi-instagram\"></i></li>\n");
      out.write("	                    <li><i class=\"bi bi-twitter\"></i></li>\n");
      out.write("	                </ul>\n");
      out.write("	            </div>\n");
      out.write("	        </section>\n");
      out.write("	        \n");
      out.write("	    <!-- 공지사항 -->\n");
      out.write("	       <div id=\"footer1-modal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" style=\"display: none; padding-right: 17px;\">\n");
      out.write("          <div class=\"modal-dialog\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("              <h1>공지 사항</h1>\n");
      out.write("                 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("             </div>\n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("               <div class=\"contents\">\n");
      out.write("		        <form action=\"/\" method=\"POST\" id=\"form__wrap\">\n");
      out.write("			          <ul class=\"terms__list\">\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                <p for=\"termsOfService\" class=\"required\">밴드 아카이브 점검 안내(07/10)</p>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                안녕하세요, 밴드아카이브입니다.\n");
      out.write("			                서버 점검으로 인해 아래의 시간 동안 서비스가 일시중지 됩니다.\n");
      out.write("			                서버 점검시간 : 2023년07월10일(목)00:00 ~ 06:00\n");
      out.write("			                긴급 요청은 @BandArchive.kr로 부탁드립니다.\n");
      out.write("			                이용에 불편을 드려 죄송합니다. 더욱 신뢰받는 서비스로 보답하겠습니다.\n");
      out.write("			                감사합니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                 <p for=\"privacyPolicy\" class=\"required\">밴드아카이브의 탄생</p>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("							밴드 아키이브 관심을 가져주셔서 감사합니다.\n");
      out.write("							더 좋은 서비스와 고객여러분의 폭넓은 니즈를 실현해 드리도록 도와드리겠습니다.\n");
      out.write("							밴드를 함께할수있는 예약, 게시판, 대화 등을 관리하고 있습니다.\n");
      out.write("							감사합니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                <p for=\"allowPromotions\"  class=\"required\">밴드 매칭 규정</p>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                밴드 아카이브를 찾아주신 여러분께 감사 인사드립니다.\n");
      out.write("			                다름이 아니라 밴드 아카이브에 지켜야할 예절이 있습니다.<br>\n");
      out.write("			                첫 번째 다름 사람에게 욕설 및 질타 금지합니다.<br>\n");
      out.write("			                두 번째 악기를 다루지 못하더라도 머라고 하지 않으며, 칭찬을 해주시기 바랍니다.<br>\n");
      out.write("			                세 번째 다같이 배우면서 실력을 키우는 입장이므로 불평 불만을 하시면 안됩니다.<br>\n");
      out.write("			                네 번째 밴드 예약을 했을시 정해진 시간이 있으므로 불가피한 사정이 아니면 취소가 불가능합니다.<br>\n");
      out.write("			                다섯번째 서로서로 정해진 약속 시간에 맞춰서 나오주시길 바랍니다.<br>\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			          </ul>\n");
      out.write("			         <div class=\"modal-footer\">\n");
      out.write("			           <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" id=\"agreebtn\">Check</button>\n");
      out.write("			         </div>\n");
      out.write("			        </form>\n");
      out.write("			      </div>\n");
      out.write("			   </div>\n");
      out.write("              </div>\n");
      out.write("           </div><!-- /.modal-content -->\n");
      out.write("         </div><!-- /.modal-dialog -->    \n");
      out.write("         \n");
      out.write("         \n");
      out.write("	    <!-- 이용약관 -->\n");
      out.write("	    <div id=\"footer2-modal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" style=\"display: none; padding-right: 17px;\">\n");
      out.write("          <div class=\"modal-dialog\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("              <h1>Terms Of Use</h1>\n");
      out.write("                 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("             </div>\n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("               <div class=\"contents\">\n");
      out.write("		        <form action=\"/\" method=\"POST\" id=\"form__wrap\">\n");
      out.write("		          <div class=\"terms__check__all\">\n");
      out.write("		            <label for=\"checkAll\">BandArchive 이용약관, 매치정보</label>\n");
      out.write("		          </div>\n");
      out.write("			          <ul class=\"terms__list\">\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                <label for=\"termsOfService\" class=\"required\">이용약관 및 서비스 </label>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                BandArchive 여러분을 환영합니다.  서비스 및 제품(이하 ‘서비스’)을 이용해 주셔서 감사합니다. 본 약관은 다양한 JUN\n");
      out.write("			                서비스의 이용과 관련하여 서비스를 제공하는  주식회사(이하 ‘서비스’)와 이를 이용하는  서비스\n");
      out.write("			                회원(이하 ‘회원’) 또는 비회원과의 관계를 설명하며, 아울러 여러분의  서비스 이용에 도움이 될 수 있는\n");
      out.write("			                유익한 정보를 포함하고 있습니다. 서비스를 이용하시거나 서비스 회원으로 가입하실 경우 여러분은 본\n");
      out.write("			                약관 및 관련 운영 정책을 확인하거나 동의하게 되므로, 잠시 시간을 내시어 주의 깊게 살펴봐 주시기\n");
      out.write("			                바랍니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                 <label for=\"privacyPolicy\" class=\"required\">개인정보 수집 및 이용 </label>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                개인정보보호법에 따라 BandArchive에 회원가입 신청하시는 분께 수집하는 개인정보의 항목, 개인정보의 수집 및\n");
      out.write("			                이용목적, 개인정보의 보유 및 이용기간, 동의 거부권 및 동의 거부 시 불이익에 관한 사항을 안내 드리오니\n");
      out.write("			                자세히 읽은 후 동의하여 주시기 바랍니다.1. 수집하는 개인정보 이용자는 회원가입을 하지 않아도 정보 검색,\n");
      out.write("			                뉴스 보기 등 대부분의 네이버 서비스를 회원과 동일하게 이용할 수 있습니다. 이용자가 메일, 캘린더, 카페,\n");
      out.write("			                블로그 등과 같이 개인화 혹은 회원제 서비스를 이용하기 위해 회원가입을 할 경우, 네이버는 서비스 이용을\n");
      out.write("			                위해 필요한 최소한의 개인정보를 수집합니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                <label for=\"allowPromotions\"  class=\"required\">매치 정보</label>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                BandArchive에서 제공하는 이벤트/혜택 등 다양한 정보를 휴대전화(BandArchive앱 알림 또는 문자), 이메일로 받아보실 수\n");
      out.write("			                있습니다. 일부 서비스(별도 회원 체계로 운영하거나 BandArchive 가입 이후 추가 가입하여 이용하는 서비스 등)의\n");
      out.write("			                경우, 개별 서비스에 대해 별도 수신 동의를 받을 수 있으며, 이때에도 수신 동의에 대해 별도로 안내하고\n");
      out.write("			                동의를 받습니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			          </ul>\n");
      out.write("			         <div class=\"modal-footer\">\n");
      out.write("			           <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" id=\"agreebtn\">Check</button>\n");
      out.write("			         </div>\n");
      out.write("			        </form>\n");
      out.write("			      </div>\n");
      out.write("			   </div>\n");
      out.write("              </div>\n");
      out.write("           </div><!-- /.modal-content -->\n");
      out.write("         </div><!-- /.modal-dialog -->\n");
      out.write("          \n");
      out.write("          \n");
      out.write("          <!-- 개인정보처리방침 -->\n");
      out.write("	    <div id=\"footer3-modal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" style=\"display: none; padding-right: 17px;\">\n");
      out.write("          <div class=\"modal-dialog\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("              <h1>Privacy Policy</h1>\n");
      out.write("                 <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">×</span></button>\n");
      out.write("             </div>\n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("               <div class=\"contents\">\n");
      out.write("		        <form action=\"/\" method=\"POST\" id=\"form__wrap\">\n");
      out.write("		          <div class=\"terms__check__all\">\n");
      out.write("		            <label for=\"checkAll\">BandArchive 개인정보지침</label>\n");
      out.write("		          </div>\n");
      out.write("			          <ul class=\"terms__list\">\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                <label for=\"termsOfService\" class=\"required\">홈페이지 회원 가입 및 관리 </label>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                회원 가입의사 확인 회원제 서비스 제공에 따른 본인 식별. 인증, 회원자격 유지 관리, 제한적 본인 확인제 시행에 \n");
      out.write("			                따른 본인확인, 서비스 부정이용방지, 만 14세 미만 아동의 개인정보처리시 법정대리인의 동의여부 확인, 각종 고지,통지 고충\n");
      out.write("			                처리등을 목적으로 개인정보를 처리합니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                 <label for=\"privacyPolicy\" class=\"required\">개인정보 수집 및 이용 </label>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                개인정보보호법에 따라 BandArchive에 회원가입 신청하시는 분께 수집하는 개인정보의 항목, 개인정보의 수집 및\n");
      out.write("			                이용목적, 개인정보의 보유 및 이용기간, 동의 거부권 및 동의 거부 시 불이익에 관한 사항을 안내 드리오니\n");
      out.write("			                자세히 읽은 후 동의하여 주시기 바랍니다.1. 수집하는 개인정보 이용자는 회원가입을 하지 않아도 정보 검색,\n");
      out.write("			                뉴스 보기 등 대부분의 네이버 서비스를 회원과 동일하게 이용할 수 있습니다. 이용자가 메일, 캘린더, 카페,\n");
      out.write("			                블로그 등과 같이 개인화 혹은 회원제 서비스를 이용하기 위해 회원가입을 할 경우, 네이버는 서비스 이용을\n");
      out.write("			                위해 필요한 최소한의 개인정보를 수집합니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			            <li class=\"terms__box\">\n");
      out.write("			              <div class=\"input__check\">\n");
      out.write("			                <label for=\"allowPromotions\"  class=\"required\">개인정보의 처리 및 보유기간</label>\n");
      out.write("			              </div>\n");
      out.write("			              <div class=\"terms__content\">\n");
      out.write("			                1. 회사는 법령에 따른 개인정보 보유, 이용기간 또는 정보주체로부터 개인정보를 수집시에 동의받은 개인정보 보유 이용기간 내에서\n");
      out.write("			                개인정보를 처리 보유합니다.\n");
      out.write("			                2. 각각의 개인정보 처리 및 보유 기간은 다음과 같습니다.\n");
      out.write("			                3. 재화 또는 서비스 제공하는데 민원인의 신원 확인, 사실조사를 위한 연락 통지, 처리결과를 통보 등의 목적으로 개인정보를 처리합니다.\n");
      out.write("			              </div>\n");
      out.write("			            </li>\n");
      out.write("			          </ul>\n");
      out.write("			         <div class=\"modal-footer\">\n");
      out.write("			           <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\" id=\"agreebtn\">Check</button>\n");
      out.write("			         </div>\n");
      out.write("			        </form>\n");
      out.write("			      </div>\n");
      out.write("			   </div>\n");
      out.write("              </div>\n");
      out.write("           </div><!-- /.modal-content -->\n");
      out.write("         </div><!-- /.modal-dialog -->\n");
      out.write("          \n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("        \n");
      out.write("  \n");
      out.write("    </footer>\n");
      out.write("    \n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/footer.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
